name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Jack Henhapl
api-version: 1.13
main: edu.whimc.worldchatprefixer.WorldChatPrefixer
load: POSTWORLD
softdepend: [Multiverse-Core]
commands:
  worldchatprefixer:
    description: Change world's chat prefix
    aliases: [wcp]
    permission: worldchatprefixer.admin
permissions:
  worldchatprefixer.admin:
    description: Main permission for WorldChatPrefixer
    default: op